version: "3.7"
services:
  app:
    build:
      args:
        user: alisson
        uid: 1000
      context: ./casafy-app/
      dockerfile: Dockerfile
    image: home
    container_name: casafy-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./casafy-app/:/var/www
      - ./.env:/var/www/.env
    networks:
      - private-net

  db:
    image: mysql:8
    container_name: casafy-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - private-net

  nginx:
    image: nginx:alpine
    container_name: casafy-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./casafy-app:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - private-net

networks:
  private-net:
    driver: bridge
